site_name: Pyshic
theme:
  name: material
  features:
    - content.code.copy

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - "Reference":
    - "Overview": reference/reference.md 
    - "julianday": reference/julianday.md

  - explanation.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  